---
apiVersion: v1
kind: Secret
metadata:
  name: huggingface-secret
type: Opaque
data:
  HF_TOKEN: aGZfYU9wZ010WEtGRFFZZkhBaEdBdmpNeVJmWVNra3hxVHR2WA== # Base64-encoded value of 'your_huggingface_secret_token'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: huggingface-cache-pvc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/huggingface-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual